name: test

on:
  push:
    branches:
      - test

jobs:
  without-env:
    runs-on: ubuntu-latest
    steps:
      - name: Testing...
        run: |
          echo "Secret: ${{ secrets.SOME_SECRET_FOR_TESTING }}"
          echo "Env var 'SOME_SECRET_FOR_TESTING': $SOME_SECRET_FOR_TESTING"
  with-env:
    runs-on: ubuntu-latest
    steps:
      - name: Testing...
        env:
          SUPER_SECRET: ${{ secrets.SOME_SECRET_FOR_TESTING }}
          SOME_SECRET_FOR_TESTING: ${{ secrets.SOME_SECRET_FOR_TESTING }}
        run: |
          echo "Secret: ${{ secrets.SOME_SECRET_FOR_TESTING }}"
          echo "Env var 'SUPER_SECRET': $SUPER_SECRET"
          echo "Env var 'SOME_SECRET_FOR_TESTING': $SOME_SECRET_FOR_TESTING"
