name: test

on:
  push:
    branches:
      - test

jobs:
  without-env:
    runs-on: ubuntu-latest
    steps:
      - name: Testing...
        run: |
          echo "secrets.SOME_SECRET_FOR_TESTING='${{ secrets.SOME_SECRET_FOR_TESTING }}'"
          echo "SUPER_SECRET='$SUPER_SECRET'"
          echo "SOME_SECRET_FOR_TESTING='$SOME_SECRET_FOR_TESTING'"

  with-env:
    runs-on: ubuntu-latest
    steps:
      - name: Testing...
        env:
          SUPER_SECRET: ${{ secrets.SOME_SECRET_FOR_TESTING }}
          SOME_SECRET_FOR_TESTING: ${{ secrets.SOME_SECRET_FOR_TESTING }}
        run: |
          echo "secrets.SOME_SECRET_FOR_TESTING='${{ secrets.SOME_SECRET_FOR_TESTING }}'"
          echo "SUPER_SECRET='$SUPER_SECRET'"
          echo "SOME_SECRET_FOR_TESTING='$SOME_SECRET_FOR_TESTING'"
